### ISSUE TITLE
Model for beer

### ISSUE THREAD

**Issue by crowandrew** [PatCeriale/Whale-Hunter#37]
As a developer
I want a beer model
So that I can store brewery information

Acceptance Criteria

- [x] create module exports
- [x] create beer variable
- [x] create name string type not null greater than 1 character
- [x] create brewery_id integer type foreign key to breweries table id
- [x] create description text type
- [x] create style_id integer type foreign key to styles table id
- [x] create abv integer type
- [x] create ibu integer type
- [x] create rating_id integer type foreign key to ratings table id

**Comment by ajm5099** [comment]
Finished setup of framework for file, unsure if belongs to breweries
